#!/usr/bin/env node
// Builds "Claude Code Router.app" and installs it in /Applications, so the app
// opens like any other: Spotlight, Launchpad, the Dock, a double click.
//
//   npm run app            build and install
//   npm run app -- --remove   uninstall
//
// What gets built is a real Mac app (its own name in the menu bar, its own Dock
// icon, its own copyright line in Get Info) around a very small launcher. The
// launcher loads main.js from THIS folder. So the app always runs the code that
// is in the repository right now: edit a file, reopen the app, and the change is
// there. Nothing has to be rebuilt after a code change. Run this again only when
// the Electron version changes or the repository moves.
//
// That also means the app is tied to this folder on this Mac. It is a shortcut
// with a proper identity, not something to hand to another person. A standalone
// build for sharing would copy the code in and needs signing and notarizing.

import { packager } from "@electron/packager";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = require(path.join(ROOT, "package.json"));
const electronVersion = require(path.join(ROOT, "node_modules/electron/package.json")).version;

const APP_NAME = "Claude Code Router";
const BUNDLE_ID = "com.stevendesignservices.cc-router";
const COPYRIGHT = "© 2026 Steven Design Services LLC. All rights reserved.";

const LSREGISTER = "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister";

const say = (s) => console.log(s);

// /Applications when it can be written to, else the per-user Applications folder.
function installDir() {
  try {
    fs.accessSync("/Applications", fs.constants.W_OK);
    return "/Applications";
  } catch {
    const mine = path.join(os.homedir(), "Applications");
    fs.mkdirSync(mine, { recursive: true });
    return mine;
  }
}

function remove() {
  let removed = false;
  for (const dir of ["/Applications", path.join(os.homedir(), "Applications")]) {
    const app = path.join(dir, APP_NAME + ".app");
    if (fs.existsSync(app)) {
      fs.rmSync(app, { recursive: true, force: true });
      say(`Removed ${app}`);
      removed = true;
    }
  }
  if (!removed) say("Nothing to remove.");
}

// The launcher: two small files, written fresh each build with this folder's
// path baked in.
function writeLauncher(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(
    path.join(dir, "package.json"),
    JSON.stringify({ name: "cc-router-launcher", productName: APP_NAME, version: pkg.version, main: "boot.js", private: true }, null, 2)
  );
  fs.writeFileSync(
    path.join(dir, "boot.js"),
    `// Generated by scripts/make-app.mjs. Loads the app from the repository, so the
// installed app always runs the current code.
const path = require("path");
const fs = require("fs");
const { app, dialog } = require("electron");

// CC_ROUTER_MAIN points the launcher at another entry file. It exists for
// development and automated checks.
const ROOT = ${JSON.stringify(ROOT)};
const entry = process.env.CC_ROUTER_MAIN || path.join(ROOT, "main.js");

if (!fs.existsSync(entry)) {
  app.whenReady().then(() => {
    dialog.showErrorBox(
      ${JSON.stringify(APP_NAME)},
      "The app's source folder was not found:\\n\\n" + ROOT +
        "\\n\\nIf the folder moved, open it in Terminal and run: npm run app"
    );
    app.quit();
  });
} else {
  require(entry);
}
`
  );
}

async function build() {
  if (process.platform !== "darwin") throw new Error("This builds a macOS app. Run it on a Mac.");
  const icon = path.join(ROOT, "build", "icon.icns");
  const out = path.join(ROOT, "dist");
  const launcher = path.join(out, "launcher-src");
  writeLauncher(launcher);

  say(`Building ${APP_NAME}.app on Electron ${electronVersion} (${process.arch})…`);
  const [built] = await packager({
    dir: launcher,
    out,
    name: APP_NAME,
    platform: "darwin",
    arch: process.arch,
    electronVersion, // must match the repository's Electron: node-pty is built against it
    icon: fs.existsSync(icon) ? icon : undefined,
    appBundleId: BUNDLE_ID,
    appVersion: pkg.version,
    appCopyright: COPYRIGHT,
    appCategoryType: "public.app-category.developer-tools",
    asar: false,
    prune: false,
    overwrite: true,
    quiet: true,
  });

  const src = path.join(built, APP_NAME + ".app");
  const dest = path.join(installDir(), APP_NAME + ".app");
  fs.rmSync(dest, { recursive: true, force: true });
  execFileSync("/usr/bin/ditto", [src, dest]); // ditto keeps the bundle's symlinks and metadata intact

  // Signing rejects Finder info and resource forks ("detritus not allowed"), and
  // an icon saved from a design tool often carries some. Clear them first.
  execFileSync("/usr/bin/xattr", ["-cr", dest]);

  // Apple Silicon refuses to run an unsigned app. This is an ad-hoc signature:
  // enough for an app built and run on the same Mac, not a Developer ID.
  execFileSync("/usr/bin/codesign", ["--force", "--deep", "--sign", "-", dest], { stdio: "ignore" });
  execFileSync("/usr/bin/codesign", ["--verify", "--deep", "--strict", dest], { stdio: "ignore" });

  // Tell LaunchServices now, so Spotlight and Launchpad find it without a delay.
  try {
    execFileSync(LSREGISTER, ["-f", dest], { stdio: "ignore" });
  } catch {
    /* it registers on first open anyway */
  }

  // Leave no second copy behind. A built .app sitting in dist/ shows up in
  // Spotlight as a twin of the installed one, and `open -a` may pick it.
  try {
    execFileSync(LSREGISTER, ["-u", src], { stdio: "ignore" });
  } catch {
    /* it was never registered */
  }
  fs.rmSync(out, { recursive: true, force: true });

  say(`Installed: ${dest}`);
  say(`It runs the code in: ${ROOT}`);
  say("Open it from Spotlight, Launchpad, or Finder. To keep it in the Dock: open it, right-click its Dock icon, Options, Keep in Dock.");
}

const args = process.argv.slice(2);
(args.includes("--remove") ? Promise.resolve(remove()) : build()).catch((e) => {
  console.error("Could not build the app: " + (e && e.message ? e.message : e));
  process.exit(1);
});
